### ISSUE TITLE
.jar file not running in Windows 10

### ISSUE THREAD

**Issue by Twilightdusk** [lashoun/upgraded-fefates-randomizer#6] opened 2022-04-15 02:38 UTC
Running on Windows 10, trying to follow the instructions but I cannot open the Fates Randomizer Beta 5-5.jar file. If I try to open it in explorer nothing happens, if I try to open it from commandline I see this error:

>java -jar "Fates Randomizer Beta 5-5.jar"
Error: Could not find or load main class main.Main
Caused by: java.lang.NoClassDefFoundError: javafx/application/Application

**Comment by lashoun** [comment] 2022-04-19 01:06
This is curious. When you say "open it in explorer" you mean double-clicking on it? And nothing happens?

**Comment by Twilightdusk** [comment] 2022-04-19 01:31
Correct, when double clicking it in explorer, nothing happens whatsoever.

**Comment by lashoun** [comment] 2022-04-19 14:18
I have tried on two different computers on Windows 10 and it works fine. Could you try to reinstall a Java Runtime Environment? The latest should do.

**Comment by Twilightdusk** [comment] 2022-04-19 14:59
That was the first thing I tried and it still wouldn't work. I have Java Version 8 Update 321, is that not the latest?

**Comment by lashoun** [comment] 2022-04-19 15:35
I suspected it but I suggested nonetheless. I'm really puzzled, and since the error is silent I don't know what else to tell you... If you have access to another computer, could you try to run it there so that we can at least know if the issue comes from your computer or is reproducible elsewhere? Sorry for not being able to help you more.

**Comment by lashoun** [comment] 2022-05-03 13:14
Closing the issue, feel free to reopen if you have an update.

**Closed as not planned by lashoun** 2022-05-03 13:14 UTC
