### ISSUE TITLE
xmltodict error

### ISSUE THREAD

**Issue by awervasdfzsd** [lashoun/upgraded-fefates-randomizer#2] opened 2021-05-20 03:09 UTC
Ran the .jar on the included GGG romfs and moved RandomizerSettings to data but get the below result when running python program,
thx

![image](https://user-images.githubusercontent.com/84488143/118913259-f4d7d200-b8dd-11eb-88fa-5fb06489f110.png)

![image](https://user-images.githubusercontent.com/84488143/118913230-e1c50200-b8dd-11eb-85c3-bdf67d18ed3f.png)

**Comment by lashoun** [comment] 2021-05-20 16:28
Hi! I've just checked on xmldict's repo and found [this issue](https://github.com/martinblech/xmltodict/issues/117). Maybe try to add the argument `encoding='windows-1252'` in the `xmltodict.parse` and `xmltodict.unparse` calls in the python script? I'm not the author of that module so I'm not sure I can help you more. You can also try to use Google Colab to run the script (I can detail a bit how to do that if needed).

**Comment by awervasdfzsd** [comment] 2021-05-21 04:50
Got it workin with a linux vm, thx for the suggestion,
btw worth noting that amiibo children and anna are required to be selected 
thx for the patch

**Comment by lashoun** [comment] 2021-05-21 10:35
Glad to hear that.
You're right, thanks for the heads-up! Since I've always selected everything, I didn't think about this. I'll update the readme.

**Comment by ZombiFoxGC** [comment] 2021-06-29 04:51
I have this same exact issue but I'm not sure what the steps are to rectify this. I would love to add the argument that you mentioned above but I have no idea how to do this. I've also tried looking up ways to fix this from others' experiences but I keep getting lost. May you please explain to me how I would try to fix this?

**Comment by lashoun** [comment] 2021-06-29 13:44
Hi friend, sorry you experience this issue. What I find strange is that I myself do not experience it even when running it on Windows (EDIT: actually I don't, I forgot about it since it's my default prompt but I actually use WSL and that may explain it)...

Here is a possible fix; try it and please let me know if it solved the problem.

First, don't forget to `git pull` to be on the latest version (otherwise the line numbers might be wrong).

Now, try to replace, in the `updated_randomizer.py` file, on line 126,
`xmltodict.parse(fxml.read())`
by
`xmltodict.parse(fxml.read(), encoding='windows-1252')`
and on line 1156,
`xmltodict.unparse(self.settings, pretty=True)`
by
`xmltodict.unparse(self.settings, pretty=True, encoding='windows-1252')`

**Comment by ZombiFoxGC** [comment] 2021-06-29 13:58
![error message](https://user-images.githubusercontent.com/86644358/123810345-510c1980-d8c0-11eb-8c17-9b6d891d16a7.PNG)
I tried changing the lines to the code you specified above but unfortunately still ended up this way. Perhaps I ran it incorrectly or need to use a VM?

**Comment by lashoun** [comment] 2021-06-29 14:54
Ok, I've tried running it with Python on Windows, got the same error, and I believe I have now fixed it. Had something to do with byte encoding.

Please pull the changes again and tell me if it works on your end! If it does, feel free to close the issue, and enjoy. :)

**Comment by ZombiFoxGC** [comment] 2021-06-29 15:09
![why is shigure dead](https://user-images.githubusercontent.com/86644358/123821679-9e40b900-d8c9-11eb-8196-e4e556c52c09.PNG)
I'm so sorry for all the issues occurring for me, but when I randomize the GGG gay fates (or the other two) Shigure seems to disappear from the list? I even looked into the output log and the randomizer settings and I can't find him in there either.
Edit: I did download the new update (I realized I didn't specify, I apologize.)

**Comment by lashoun** [comment] 2021-06-29 15:21
No problem at all, it's kinda useless to provide a randomizer if I'm the only one who can run it.

Did you randomize the children with the `jar` file? If you didn't, you have to use the option to ban children when running the Python script (`--ban-children` or `-bc`), otherwise it will search for the children in the settings and won't find them since they, well, aren't there.

That is to say, you have to run `python updated_randomizer.py -bc`. There are similar options for Anna and the Amiibo characters.

**Comment by ZombiFoxGC** [comment] 2021-06-29 15:30
I did select randomize children but it seems they all disappeared whether or not I pick that option, strangely enough. Do you think it might be a problem with the original randomizer? I've been using beta 5-1 before this with no issue, I didn't even notice it was beta 5-5.

**Comment by lashoun** [comment] 2021-06-29 15:41
I was the one who changed a few things inside the `jar` because there were some errors in the data it contained. I had a changelog but I unknowingly deleted it at some point. The thing is, it shouldn't have changed the behaviour of the randomizer. When you used beta 5-1, did you check the `Join Order` option? Because it seems that if you randomize the children with it, it does work, but if you don't check `Join Order`, as you say, the children do not get randomized... If you really want to randomize the children without changing the join order, could you perhaps use the beta 5-1 version while I investigate the issue?

EDIT: just tried with beta 5-1: the issue was already there. If you want to randomize the children, you need to check the "Join Order" option.

**Comment by ZombiFoxGC** [comment] 2021-06-29 15:58
With the Join Order randomized everything seems to be working fine, thank you very much for your effort and time!

Edit: I apologize I have no idea how to close the issue thread.

**Comment by lashoun** [comment] 2021-06-29 16:23
That's great! Thank you for your patience.

Under the message input box there is a button named "Close the issue". Do it when you have confirmed that your randomized game runs without issues. :)

**Comment by ZombiFoxGC** [comment] 2021-06-29 16:30
Sorry to sound dumb for one more minute but I put the new randomized main directory files into the fatese mod folder and it's not popping up randomized, does it need to be an installed cia? (I've been using randomized decrypted 3ds files)

Unfortunately for some reason I don't have the Close Issue button on my screen, it might be because I'm too new?

**Comment by lashoun** [comment] 2021-06-29 17:01
Haha, it's all right. Are you using Citra or a 3DS with CFW? If you use Citra, in the mods folder you have to create a `romfs` folder and put the four folders (`castle`, `GameData`, `m`, and `Scripts`) inside the `romfs` folder.

**Comment by ZombiFoxGC** [comment] 2021-06-29 17:14
First time using Citra for randomizing, and haven't used my CFW 3DS for it in years - may it's small SD card rest in piece, totally forgot about the romfs folder! All I remember was putting it into the fatese folder. Everything seems to be running now, thank you so much!

**Comment by lashoun** [comment] 2021-06-29 17:17
You're welcome. Enjoy your run!

**Closed as completed by lashoun** 2021-06-29 17:17 UTC
