### ISSUE TITLE
Issues with Birthright

### ISSUE THREAD

**Issue by BeegBoi4** [lashoun/upgraded-fefates-randomizer#3] opened 2021-10-22 03:43 UTC
I ran into quite some issues so apologies for the long read, 
For context, I am using a homebrewed 3ds with luma ver 10.2.1 with my cartridge copy of birthright with all the paths purchased.
So in my first attempt, I did everything correctly for sure, the randomizer worked fine until chapter 6 when the characters that joined me were the exact same as the ones that appear in vanilla, along with their weapons from their non-randomizing classes. Thinking it was a bug with the GGG version, I tried with the upgraded fates version, which crashes immediately during the tutorial in chapter 1. As a final attempt, I attempted it with vanilla fates and it works just fine but it sucks considering the supports would be a nice addition

P.s: You don't have to do this but I believe both gay fates and GGG are a bit outdated and an update would be nice

**Comment by lashoun** [comment] 2021-10-28 14:07
This is strange. Which route did you check with the jar file ? Birthright or All Routes?

As for the update, I will try to do it when I have some free time. Thanks for mentioning it; I'm surprised people are still adding supports.

**Comment by lashoun** [comment] 2021-10-28 14:22
Actually, properly updating Gay Fates and GGG would mean redoing everything from scratch since I lost the config files from Paragon. Mixing the mods in the randomizer was a pretty time-consuming process requiring trial and error for compatibility issues and, to be frank, I will probably never be bothered enough to do it again myself. I will still try a quick fix in the near future but I cannot give any guarantee that it actually works; someone will have to test it.

**Comment by BeegBoi4** [comment] 2021-10-28 15:06
For the modified versions, did select all the paths, however, when trying with the vanilla fates, I did notice that it did not give any other options and in my playthrough, only hoshidan units were modified, all nohrian units were still the same. So I did some experimenting myself. I obtained a copy of the Special edition and the GGG version worked perfectly fine, so I think the issue might be related to the game cartridge rather than the randomizer, however, I have yet to test the upgraded version.
As for the update, I understand, I'm very new to this whole modding 3ds games so I can imagine how tedious it must be, but Im willing test the quick fix. Thank you for your time.

**Comment by lashoun** [comment] 2021-11-03 23:29
Now that you mention it, it makes sense. The modded content comes from the Special Edition so it is understandable that it does not work perfectly with a Birthright version, even with all paths. The roms must have a few differences. I updated the readme accordingly.

I've checked a bit and I believe GGG is up to date since it hasn't had any updates for a few years already. As for Gay Fates, the current randomizer should have some added supports from the unofficial repository on GameBanana since I remember tinkering with it. I will try to add the new ones this weekend; I'll let you tell me if it worked. :)

**Comment by BeegBoi4** [comment] 2021-11-09 05:51
Thank you for your help and sorry for any inconvenience. Im happy to help in any way. By the way do you want me to close this issue?

**Comment by lashoun** [comment] 2021-11-09 09:49
No problem, thank you for raising this issue. I'll close it myself once I push the updated Gay Fates. Don't get your hopes up too much though, the fix might not work. On the bright side, there are already quite a lot of supports.

**Comment by lashoun** [comment] 2021-11-19 22:01
@BeegBoi4 I've added a new branch named "supports" where you can find a `fates_gay2_decompressed.7z` file in the `romfs` folder. Basically, I took the latest unofficial gay fates patch and simply copy and pasted it over the previous files. Tell me how it works.

**Comment by lashoun** [comment] 2021-11-22 00:50
Update: the file is now named `fates_gay_v140_decompressed.7z` and it should work like a charm. Closing the issue, feel free to reopen if there is a problem!

**Closed as completed by lashoun** 2021-11-22 00:50 UTC

**Comment by lashoun** [comment] 2021-11-22 00:57
Removed support branch.

**Comment by BeegBoi4** [comment] 2021-11-22 15:12
Thanks for your help, I actually got really lucky and managed to get Camilla as Felicia, who has new supports added and will use to tell if the update worked or not, will tell you if It does but I need to progress a bit.

**Comment by BeegBoi4** [comment] 2021-12-01 05:52
So after testing for a bit, I can say the update works sorta, I used the fates_gay2 version so maybe this was fixed with the new version you posted. I do think it worked since i remember playing previously and  there was no c conv with azura and beruka before but now it's there but for some reason many supports, including some who were said to be recently added, only happen, without any conv, I don't know if this is the add on or not. I will try the new version soon to see if this is just some bug.

**Comment by lashoun** [comment] 2021-12-01 07:24
There are indeed quite many supports who just happen without conversation in the add-on, it's not a bug. Yes, please try the new version, the gay2 one was admittedly a hurriedly-made quick fix. The gay1.4.0 version's main improvement is that all supports are available on all routes.

**Comment by lashoun** [comment] 2022-01-11 20:31
Closing the issue, feel free to reopen if needed!

**Comment by BeegBoi4** [comment] 2022-03-19 01:42
Hello, sorry for the delay for the response, but I finished and I can say its playable for sure but there are some issues that could be a bit of an issue:
- First, a random character, like my "Felicia", cannot be supported in any way, even if other units do say support is possible
- Second, some children paralogues will crash for some reason, this occurs after the little intro 
- And Lastly, for some reason in the conquest endgame, when "Takumi" does its first wave attack, the game will crash
Most of these issues are honestly just a bit inconvenient but are worth noting.

**Comment by lashoun** [comment] 2022-06-16 14:18
Hi, I completely forgot to answer but thank you for reporting those issues since I have not encountered any of these myself (I admittedly did not go all the way to Conquest endgame). Hopefully you enjoyed the experience still.
